### ISSUE TITLE
os.EX_OK not available on Windows

### ISSUE THREAD

**Issue by KyleKing** [dlint-py/dlint#17]
FYI: [`os.EX_OK` isn't available on Windows](https://docs.python.org/3.9/library/os.html#os.EX_OK) and fails when running `flake8 --print-dlint-linters` 

Not sure what the appropriate substitute is, but I'd be happy to test any changes

https://github.com/dlint-py/dlint/blob/828a156eead73e4140ddc6925ff85bf65424fabb/dlint/extension.py#L46

**Comment by mschwager** [comment]
Thanks for opening this! I'll take a look and make sure we run this flag in AppVeyor so we catch issues like this in the future.

**Comment by SamuelMarks** [comment]
FYI - I added Windows support ~3 years ago - https://bugs.python.org/issue44321
