### ISSUE TITLE
Relationship to bandit

### ISSUE THREAD

**Issue by MartinThoma** [dlint-py/dlint#34]
What is the relationship between dlint and [bandit](https://pypi.org/project/bandit/)?

What I can see:

* dlint is a flake8 plugin while bandit is a project of its own (there is [flake8-bandit](https://pypi.org/pypi/flake8-bandit), though)
* bandit is part of [PyCQA](https://meta.pycqa.org/en/latest/) which includes also flake8 and flake8-bugbear
* bandit has 2700 GitHub stars, dlint has 45

Could somebody maybe point out reasons to use one or the other? Do you maybe use both together? Is there an overlap between the communities?

**Comment by mschwager** [comment]
Good question! This is addressed in our FAQs: https://github.com/dlint-py/dlint/tree/master/docs#why-not-bandit
