### ISSUE TITLE
Remove use of deprecated ast classes and methods

### ISSUE THREAD

**Issue by mschwager** [dlint-py/dlint#4]
Per the [Python 3.8 release notes](https://docs.python.org/3.9/whatsnew/3.8.html):

> ast classes Num, Str, Bytes, NameConstant and Ellipsis are considered deprecated and will be removed in future Python versions. Constant should be used instead. (Contributed by Serhiy Storchaka in bpo-32892.)
> 
> ast.NodeVisitor methods visit_Num(), visit_Str(), visit_Bytes(), visit_NameConstant() and visit_Ellipsis() are deprecated now and will not be called in future Python versions. Add the visit_Constant() method to handle all constant nodes. (Contributed by Serhiy Storchaka in bpo-36917.)

This isn't immediately necessary, but it's worth tracking. It's not clear when this change will happen, so we don't need a definite timeline. If we can wait until Python 2.7 support is dropped (#17) then this change will be a bit easier since many of these classes/methods are used in 2.7. For example, Dlint makes use of `ast.Str` and `ast.NameConstant`.

**Comment by clavedeluna** [comment]
Can be done once all versions including py3.7 are deprecated

**Comment by hannob** [comment]
Update: These are now actually removed in alpha versions of python 3.14.

I tried upgrading one of my project's CI to 3.14-dev, and dlint fails due to ast.Str:
https://github.com/badkeys/badkeys/actions/runs/11539580878/job/32119419377

**Comment by mschwager** [comment]
@hannob hi there, this should be fixed in https://github.com/dlint-py/dlint/commit/0c31764dd365b3c84d91781bc7d62893174869e7.

I've also released Dlint 0.16.0 with the changes: https://pypi.org/project/dlint/0.16.0/
