### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by clavedeluna** [dlint-py/dlint#51]
Python 3.6 was deprecated [8 months ago](https://endoflife.date/python) so it would be good to drop it. Locations to update:

1.  setup.py 3.6 mention
2. look for any usage of `sys.version_info` that needs to be updated accordingly

**Comment by mschwager** [comment]
Done! https://github.com/dlint-py/dlint/commit/d05a692be76455d3e33112f473c7a8e4c11ba627
